<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="P_Simulator" Id="{efa2403d-d7ed-4f84-a9c5-e4543ee5f98b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_Simulator
VAR
	fbSimulator 	: FB_CraneSimulator;
	bSimulatorOn 	: BOOL;
	fCylPos 		: LREAL;
	fUDCV			: LREAL;
	fPpBar			: LREAL;
	fPrBar			: LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbSimulator(
	ssMethodType 	:= BOOL_TO_SINT(bSimulatorOn),
	uDCV			:= fUDCV,
	xm 				=> fCylPos,
	ppbar			=> fPpBar,
	prbar			=> fPrBar
);


P_SimulatorExample();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>